document.write("");
document.write("<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>");
document.write("<html xmlns='http://www.w3.org/1999/xhtml'>");
document.write("<head>");
document.write("<meta http-equiv='Content-Type' content='text/html; charset=gb2312' />");
document.write("<title>管理|人物</title>");
document.write("");
document.write("</head>");
document.write("");
document.write("<body><table width='98%' border='0' cellspacing='0' cellpadding='0'>");
document.write("  <tr>");
document.write("    <td height='36' colspan='2' valign='middle' background='http://211.154.164.205/img/end_n_bg3.gif' style='padding-left:10px;'><strong>管理·人物</strong></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan='2'>      </td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align='center' style='border:1px #cccccc solid' width='65'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>  <td id='picList_1'> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>      <td>        <div align='center'><a href='http://ceo.icxo.com/htmlnews/2012/12/10/1449069_0.htm' target='_blank'><img src='http://images4.icxo.com/201212/201212109695moyan2.jpg' width='80' height='60' border='0'></a></div>      </td></tr><tr>      <td align='center'> <a href='http://ceo.icxo.com/htmlnews/2012/12/10/1449069_0.htm'target='_blank' class='black'>诺贝尔文..</a>      </td></tr></table>  </td></tr></table>");
document.write("</td>");
document.write("    <td rowspan='3' style='padding-left:5px'><table width='100%' border='0' cellspacing='0' cellpadding='0'>");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2012/12/11/1449097.htm' target='_blank' class='menu5'>职场生存法则：如何有效应对职场</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2012/12/11/1449096_0.htm' target='_blank' class='menu5'>漫谈民营企业的现状以及实现快速</a> </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  ");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://brand.icxo.com/htmlnews/2012/10/16/1447888_0.htm' target='_blank' class='menu5'>“中国时代”的民企品牌之路</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://brand.icxo.com/htmlnews/2010/05/10/1411140_0.htm' target='_blank' class='menu5'>成就国际品牌有没有捷径？</a> </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  ");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://elab.icxo.com/htmlnews/2012/12/10/1449079.htm' target='_blank' class='menu5'>万元创业项目大推荐</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://elab.icxo.com/htmlnews/2012/12/10/1449078.htm' target='_blank' class='menu5'>盘点2012创业十大火爆项目</a> </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  ");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://mkt.icxo.com/htmlnews/2012/10/22/1448001.htm' target='_blank' class='menu5'>刘杰克：谈以产品为战略核心的品</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://mkt.icxo.com/htmlnews/2012/08/27/1447365.htm' target='_blank' class='menu5'>刘杰克：从战略战术角度谈815</a> </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://office.icxo.com/htmlnews/2012/12/10/1409846.htm' target='_blank' class='menu5'>2012最新英文简历模板：土建</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://office.icxo.com/htmlnews/2012/12/10/1409844.htm' target='_blank' class='menu5'>2012最新英文简历范文：网络</a> </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://school.icxo.com/htmlnews/2012/12/11/1407172_0.htm' target='_blank' class='menu5'>顾湘陵简历 顾湘陵家庭背景 顾</a></td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://school.icxo.com/htmlnews/2012/12/10/1409850.htm' target='_blank' class='menu5'>2000年诺贝尔文学奖获得者高</a></td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("");
document.write("</table>");
document.write("</td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align='center' style='border:1px #cccccc solid'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>  <td id='picList_1'> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>      <td>        <div align='center'><a href='http://ceo.icxo.com/htmlnews/2012/12/07/1449050_0.htm' target='_blank'><img src='http://images4.icxo.com/201212/20121272736liyanhong2.jpg' width='80' height='60' border='0'></a></div>      </td></tr><tr>      <td align='center'> <a href='http://ceo.icxo.com/htmlnews/2012/12/07/1449050_0.htm'target='_blank' class='black'>百度李彦..</a>      </td></tr></table>  </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align='center' valign='middle' style='border:1px #cccccc solid'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>  <td id='picList_1'> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=black><tr>      <td>        <div align='center'><a href='http://ceo.icxo.com/htmlnews/2012/12/07/1449045_0.htm' target='_blank'><img src='http://images4.icxo.com/201212/20121271521beisuosi2.jpg' width='80' height='60' border='0'></a></div>      </td></tr><tr>      <td align='center'> <a href='http://ceo.icxo.com/htmlnews/2012/12/07/1449045_0.htm'target='_blank' class='black'>六条管理..</a>      </td></tr></table>  </td></tr></table>");
document.write("</td>");
document.write("  </tr>");
document.write("  ");
document.write("</table>");
document.write("</body>");
document.write("</html>");
document.write("");
document.write("");
