document.write("");
document.write("");
document.write("<html>");
document.write("<head>");
document.write("<title>世界经理人_世界计算机:互联网|电信|科技资讯|网络游戏|IT经理人|电子商务|IT企业|软件下载|杀毒软件|电子产品|卡巴斯基激活码|小游戏</title>");
document.write("<META NAME='keywords' CONTENT='互联网,电信,科技资讯,网络游戏,电子商务,IT企业,IT经理人,软件下载,杀毒软件,it资讯,IT人物,电子产品,卡巴斯基激活码,it调查报告,小游戏,中国移动,诺基亚,瑞星,摩托罗拉,联想,google,戴尔,微软,惠普,华为,三星,金山,qq,迅雷,pplive,跑跑卡丁车,msn,千千静听,BT下载'>");
document.write("<META NAME='descripiton' CONTENT='世界计算机频道（it.icxo.com）是中国领先的IT信息与商务门户,提供科技资讯、新闻、IT产品、IT企业介绍、IT人物访谈、IT业界、电信、互联网、企业内幕、科技产业资讯、各种软件下载、驱动下载、杀毒软件、高速安全下载、是及时权威的产业及事件报道的信息平台，同时将手机、数码、笔记本等数码产品及软件下载一网打尽。资讯中心,人物报道,产品评论,企业观察,商业科技,战略管理等8个大型频道，每天发布大量各类产品测评信息及文章专题，是IT行业的厂商,经销商,IT产品,解决方案的提供场所。'>");
document.write("<meta content='it.icxo.com,世界经理人版权所有' name='copyright' />");
document.write("<meta name='robots' content='index,follow' />");
document.write("<meta name='googlebot' content='index,follow' />");
document.write("<meta name='Inktomi Slurp' content='index,follow' />");
document.write("<meta name='SpiderMan' content='index,follow' />");
document.write("<meta name='crawl' content='index,follow' />");
document.write("<meta name='BaiDuSpider' content='index,follow' />");
document.write("<meta name='AskJeeves' content='index,follow' />");
document.write("<meta name='AYahoo Vertical Crawler' content='index,follow' />");
document.write("<meta name='MSNBot' content='index,follow' />");
document.write("<meta name='psbot' content='index,follow' />");
document.write("<meta name='*bot' content='index,follow' />");
document.write("<link href='http://it.icxo.com/01style.css' rel='stylesheet' type='text/css'>");
document.write("<style type='text/css'>");
document.write("<!--");
document.write(".grey {");
document.write("	border-left-width: 1px;");
document.write("	border-top-style: solid;");
document.write("	border-right-style: none;");
document.write("	border-bottom-style: none;");
document.write("	border-left-style: solid;");
document.write("	border-left-color: #999999;");
document.write("	border-top-width: 1px;");
document.write("	border-top-color: #999999;");
document.write("}");
document.write("a.cnn  {");
document.write("	font-family: '宋体', 'Verdana';");
document.write("	font-size: 12px;");
document.write("	line-height: 180%;");
document.write("	color: #333333;");
document.write("	text-decoration: none;");
document.write("");
document.write("}");
document.write("a.cnn:hover {");
document.write("	font-family: '宋体', 'Verdana';");
document.write("	font-size: 12px;");
document.write("	line-height: 180%;");
document.write("	text-decoration: underline;");
document.write("	color: #666666;");
document.write("");
document.write("}");
document.write("");
document.write("a.cnn:visited {");
document.write("	font-family: '宋体', 'Verdana';");
document.write("	font-size: 12px;");
document.write("	line-height: 180%;");
document.write("	color: #666666;");
document.write("}");
document.write(".newxiangguancontent {	PADDING-BOTTOM: 6px; PADDING-LEFT: 6px; PADDING-RIGHT: 6px; PADDING-TOP: 6px; TEXT-ALIGN: left; WIDTH: 100%");
document.write("}");
document.write(".ceo {	font-size: 12px;");
document.write("	font-weight: bold;");
document.write("	color: #000000;");
document.write("}");
document.write(".style18 {	color: #000000;");
document.write("	font-weight: bold;");
document.write("}");
document.write(".rightbody {	font-size: 12px;");
document.write("	line-height: 22px;");
document.write("	color: #677eaa;");
document.write("	font-family: '宋体';");
document.write("");
document.write("-->");
document.write(".pic_space {padding:1px;border:1px solid #cccccc}");
document.write(".pic_space {padding:1px;border:1px solid #cccccc}");
document.write(".style19 {font-size: 12px}");
document.write("a:visited {");
document.write("	color: #000000;");
document.write("}");
document.write(".style7 {color: #FF0000}");
document.write("body {");
document.write("	margin-bottom: 0px;");
document.write("	margin-top: 0px;");
document.write("}");
document.write("-->");
document.write("</style>");
document.write("<body>");
document.write("<table width='100%'  border='0' cellpadding='0' cellspacing='0'>");
document.write("  <tr>");
document.write("    <td height='36' colspan='2' valign='middle' background='http://211.154.164.205/img/end_n_bg3.gif'><img src='http://211.154.164.205/img/hqxilan01.gif' /><strong><a href='http://it.icxo.com/gengxin.html' target='_blank'>世界计算机</a></strong></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan='2'></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan='2' align='right'><table width='100%'  border='1' cellpadding='0' cellspacing='0' bordercolor='#E1E1E1'>");
document.write("      <tr></tr>");
document.write("      <tr bordercolor='#E1E1E1'>");
document.write("        <td height='120'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>  <td> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>      <td>        <div align='center'><a href='http://it.icxo.com/htmlnews/2009/03/05/1344659.htm' target='_blank' title='苹果3G版iPhone充电器着火被烧焦(图) '><img src='http://images1.icxo.com/20093/20093556512.jpg' width='110' height='90' border='0'></a></div>      </td></tr></table>  </td></table>");
document.write("");
document.write("          <div align='center'></div></td>");
document.write("        <td height='120'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>  <td> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>      <td>        <div align='center'><a href='http://it.icxo.com/htmlnews/2009/02/04/1337296.htm' target='_blank' title='显示3D效果的手机日立Wooo问世'><img src='http://images1.icxo.com/20092/2009240178200902040903316e54b.jpg' width='110' height='90' border='0'></a></div>      </td></tr></table>  </td></table>");
document.write("");
document.write("          <div align='center'></div></td></tr>");
document.write("      <tr bordercolor='#E1E1E1'>");
document.write("        <td height='120'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>  <td> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>      <td>        <div align='center'><a href='http://it.icxo.com/htmlnews/2009/01/16/1333630.htm' target='_blank' title='美国安全局的防泄密手机 售价2万元'><img src='http://images1.icxo.com/20091/200911686112.jpg' width='110' height='90' border='0'></a></div>      </td></tr></table>  </td></table>");
document.write("");
document.write("          <div align='center'></div></td>");
document.write("        <td height='120'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>  <td> <table width='100%' border='0' cellspacing='0' cellpadding='0' class=STYLE9><tr>      <td>        <div align='center'><a href='http://it.icxo.com/htmlnews/2009/01/16/1333629.htm' target='_blank' title=''奥巴马'手机仅300元'><img src='http://images1.icxo.com/20091/200911688552009011608304177599.jpg' width='110' height='90' border='0'></a></div>      </td></tr></table>  </td></table>");
document.write("");
document.write("          <div align='center'></div></td></tr>");
document.write("    </table>");
document.write("        <table width='100%' border='0' align='center' cellpadding='0' cellspacing='1' bgcolor='#FFFFFF'>");
document.write("          <tr align='center'>");
document.write("            <td height='20' valign='middle' bgcolor='efefef'><strong> 热点</strong>： <a href='http://it.icxo.com/top_bigclass_3807.htm' target='_blank'>互联网</a> | <a href='http://it.icxo.com/top_view_21652_1.htm' target='_blank'>IT人物</a> | <a href='http://it.icxo.com/top_bigclass_3859.htm' target='_blank'> 软件下载</a> </td>");
document.write("          </tr>");
document.write("        </table>");
document.write("      <table width='100%' border='0' align='center' cellpadding='2' cellspacing='0'>");
document.write("          <tr>");
document.write("            <td>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=font_cj2><tr><td height=23 class=font_cj2><img src=/img/dot.gif>&nbsp;<a href='http://it.icxo.com/htmlnews/2009/03/26/1349456.htm' target='_blank' class='font_cj2'>愚人节黑客可能发动史上最强网络攻击</a></td></tr><tr><td height=23 class=font_cj2><img src=/img/dot.gif>&nbsp;<a href='http://it.icxo.com/htmlnews/2009/03/26/1349292.htm' target='_blank' class='font_cj2'>三运营商3G功能难互通 短时间内无法实现</a></td></tr><tr><td height=23 class=font_cj2><img src=/img/dot.gif>&nbsp;<a href='http://it.icxo.com/htmlnews/2009/03/26/1349290.htm' target='_blank' class='font_cj2'>九城失去魔兽 中国网游将会怎样?</a></td></tr><tr><td height=23 class=font_cj2><img src=/img/dot.gif>&nbsp;<a href='http://it.icxo.com/htmlnews/2009/03/26/1349289_0.htm' target='_blank' class='font_cj2'>暴风影音身陷官司泥潭 经营模式面临生死劫</a></td></tr><tr><td height=23 class=font_cj2><img src=/img/dot.gif>&nbsp;<a href='http://it.icxo.com/htmlnews/2009/03/26/1349282.htm' target='_blank' class='font_cj2'>谷歌CEO施密特家人及朋友常免费乘坐谷歌飞机 </a></td></tr></table>");
document.write("</td>");
document.write("          </tr>");
document.write("      </table></td>");
document.write("  </tr>");
document.write("</table>");
document.write("</body>");
document.write("</html>");
