document.write("");
document.write("");
document.write("<html>");
document.write("");
document.write("<head>");
document.write("");
document.write("");
document.write("<meta content='oxford.icxo.com,世界经理人版权所有' name='copyright' />");
document.write("");
document.write("<meta name='BaiDuSpider' content='index,follow' />");
document.write("");
document.write("<meta name='Inktomi' content='index,follow' />");
document.write("");
document.write("<meta name='MSNBot' content='index,follow' />");
document.write("");
document.write("<meta name='robots' content='index,follow' />");
document.write("");
document.write("<meta name='googlebot' content='index,follow'/>");
document.write("<link href='http://oxford.icxo.com/01style.css' rel='stylesheet' type='text/css'>");
document.write("");
document.write("<style type='text/css'>");
document.write("");
document.write("<!--");
document.write("");
document.write(".grey {");
document.write("");
document.write("	border-left-width: 1px;");
document.write("");
document.write("	border-top-style: solid;");
document.write("");
document.write("	border-right-style: none;");
document.write("");
document.write("	border-bottom-style: none;");
document.write("");
document.write("	border-left-style: solid;");
document.write("");
document.write("	border-left-color: #999999;");
document.write("");
document.write("	border-top-width: 1px;");
document.write("");
document.write("	border-top-color: #999999;");
document.write("");
document.write("}");
document.write("");
document.write("a.cnn  {");
document.write("");
document.write("	font-family: '宋体', 'Verdana';");
document.write("");
document.write("	font-size: 12px;");
document.write("");
document.write("	line-height: 180%;");
document.write("");
document.write("	color: #333333;");
document.write("");
document.write("	text-decoration: none;");
document.write("");
document.write("");
document.write("");
document.write("}");
document.write("");
document.write("a.cnn:hover {");
document.write("");
document.write("	font-family: '宋体', 'Verdana';");
document.write("");
document.write("	font-size: 12px;");
document.write("");
document.write("	line-height: 180%;");
document.write("");
document.write("	text-decoration: underline;");
document.write("");
document.write("	color: #666666;");
document.write("");
document.write("");
document.write("");
document.write("}");
document.write("");
document.write("");
document.write("");
document.write("a.cnn:visited {");
document.write("");
document.write("	font-family: '宋体', 'Verdana';");
document.write("");
document.write("	font-size: 12px;");
document.write("");
document.write("	line-height: 180%;");
document.write("");
document.write("	color: #666666;");
document.write("");
document.write("}");
document.write("");
document.write(".newxiangguancontent {	PADDING-BOTTOM: 6px; PADDING-LEFT: 6px; PADDING-RIGHT: 6px; PADDING-TOP: 6px; TEXT-ALIGN: left; WIDTH: 100%");
document.write("");
document.write("}");
document.write("");
document.write(".style5 {font-size: 14px;color: #333333;}");
document.write("");
document.write(".style6 {");
document.write("");
document.write("	color: #FF0000;");
document.write("");
document.write("	font-weight: bold;");
document.write("");
document.write("}");
document.write("");
document.write(".ceo {	font-size: 12px;");
document.write("");
document.write("	font-weight: bold;");
document.write("");
document.write("	color: #000000;");
document.write("");
document.write("}");
document.write("");
document.write(".style18 {	color: #000000;");
document.write("");
document.write("	font-weight: bold;");
document.write("");
document.write("}");
document.write("");
document.write(".pic_space {padding:1px;border:1px solid #cccccc}");
document.write("");
document.write(".rightbody {font-size: 12px;");
document.write("");
document.write("	line-height: 22px;");
document.write("");
document.write("	color: #677eaa;");
document.write("");
document.write("	font-family: '宋体';");
document.write("");
document.write("");
document.write("");
document.write("-->");
document.write("");
document.write(".pic_space {padding:1px;border:1px solid #cccccc}");
document.write(".style11 {color: #FFFFFF;");
document.write("	font-weight: bold;}");
document.write(".ht150 {font-size: 12px;line-height:150%;}");
document.write("body {");
document.write("	margin-bottom: 0px;");
document.write("}");
document.write("");
document.write("-->");
document.write("");
document.write("</style>");
document.write("");
document.write("<meta http-equiv='Content-Type' content='text/html; charset=gb2312'>");
document.write("<body>");
document.write("<table width='100%' height='5' border='0' align='center' cellpadding='0' cellspacing='0'>");
document.write("  <tr></tr>");
document.write("</table>");
document.write("<table  border='0' cellspacing='0' cellpadding='0'>");
document.write("  <tr>");
document.write("    <td height='36' colspan='2' valign='middle' background='http://211.154.164.205/img/end_n_bg3.gif'><img src='http://211.154.164.205/img/hqxilan01.gif' /><strong> 管理精华</strong></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan='2'></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan='2' align='right'><table width='97%' border='0' align='center' cellpadding='2' cellspacing='2' bgcolor='#FFFFFF'>");
document.write("      <tr align='center'>");
document.write("        <td width='30%' valign='middle'><a href='http://oxford.icxo.com/top_view_17723_1.htm' target='_blank'><img src='http://images5.icxo.com/20087/200871523781.jpg' alt='' width='80' height='80' border='0' /></a></td>");
document.write("        <td width='30%' valign='middle'><a href='http://oxford.icxo.com/top_view_17770_1.htm' target='_blank'><img src='http://images5.icxo.com/20087/200871523782.jpg' alt='' width='80' height='80' border='0' /></a></td>");
document.write("        <td width='30%' valign='middle'><a href='http://oxford.icxo.com/top_view_17723_1.htm' target='_blank'><img src='http://images5.icxo.com/20087/200871523783.jpg' alt='' width='80' height='80' border='0' /></a></td>");
document.write("      </tr>");
document.write("    </table>");
document.write("      <table width='97%' border='0' align='center' cellpadding='2' cellspacing='2' bgcolor='#FFFFFF'>");
document.write("        <tr align='center'>");
document.write("          <td  ><a href='http://oxford.icxo.com/top_view_17723_1.htm' target='_blank'>香港第一富姐</a></td>");
document.write("          <td  valign='top'><a href='http://oxford.icxo.com/top_view_17770_1.htm' target='_blank'>加班最多几大行业</a></td>");
document.write("          <td  valign='top'><a href='http://oxford.icxo.com/top_view_17723_1.htm' target='_blank'>北大校花变'财女'</a></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width='97%' border='0' align='center' cellpadding='0' cellspacing='1' bgcolor='#FFFFFF'>");
document.write("        <tr align='center'>");
document.write("          <td height='20' valign='middle' bgcolor='efefef'><strong> 热点</strong>： <a href='http://oxford.icxo.com/tol/' target='_blank'> 在线培训</a> | <a href='http://oxford.icxo.com/test' target='_blank'>职场测试 </a> | <a href='http://oxford.icxo.com/tools.jsp' target='_blank'> 管理工具</a> </td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width='97%' border='0' align='center' cellpadding='2' cellspacing='0'>");
document.write("        <tr>");
document.write("          <td><span style='padding-left:10px;'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/10/1380128.htm' target='_blank' class='menu5'>职场双语:印度人的办</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/10/1380127.htm' target='_blank' class='menu5'>求伯君：技术天才的财</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/10/1380124.htm' target='_blank' class='menu5'>专家：体会职场生存的</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/10/1380089.htm' target='_blank' class='menu5'>心理学与管理:目击证</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/10/1380106.htm' target='_blank' class='menu5'>别让职场压力赶走快乐</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/09/1380130.htm' target='_blank' class='menu5'>《贞观长歌》中的领袖</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/09/1379949_0.htm' target='_blank' class='menu5'>论:优秀员工和普通员</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/09/1380084.htm' target='_blank' class='menu5'>从《黑天鹅》看不确定</a> </td></tr></table>");
document.write("</span></td>");
document.write("          <td><span style='padding-left:10px;'>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table border=0  cellpadding=0 cellspacing=0 class=menu5><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/09/1380131.htm' target='_blank' class='menu5'>经理人角色转型：从管</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379890_0.htm' target='_blank' class='menu5'>非常时期，男女消费力</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379862_0.htm' target='_blank' class='menu5'>时装从“中国制造”到</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379856.htm' target='_blank' class='menu5'>企业文化超前 企业必</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379843_0.htm' target='_blank' class='menu5'>警惕:企业裁员中的口</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379839.htm' target='_blank' class='menu5'>福布斯公布美国黑人富</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379701_0.htm' target='_blank' class='menu5'>企业如何抓住'农村市</a> </td></tr><tr><td height=23 class=menu5><img src=/img/dot.gif>&nbsp;<a href='http://oxford.icxo.com/htmlnews/2009/05/08/1379676_0.htm' target='_blank' class='menu5'>分析:六种吃掉企业利</a> </td></tr></table>");
document.write("</span></td>");
document.write("        </tr>");
document.write("      </table></td>");
document.write("  </tr>");
document.write("</table>");
document.write("<table width='97%' align='center' cellpadding='2' cellspacing='0'>");
document.write("  <tr></tr>");
document.write("</table>");
document.write("");
document.write("</body>");
document.write("");
document.write("</html>");
