document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\">");
document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln("body {");
document.writeln("	margin-left: 1px;");
document.writeln("	margin-top: 1px;");
document.writeln("}");
document.writeln(".top:link{font-size:12px;color:#FFCC00;font-weight:bold;line-height:20px; text-decoration:none;}");
document.writeln(".top:visited{font-size:12px;color:#FFCC00;font-weight:bold;line-height:20px; text-decoration:none;}");
document.writeln(".top:hover{font-size:12px;color:#FFCC00;font-weight:bold;line-height:20px; text-decoration:none;}");
document.writeln(".top:active{font-size:12px;color:#FFCC00;font-weight:bold;line-height:20px; text-decoration:none;}");
document.writeln(".topwhite:link{font-size:12px;color:#FFFFFF;line-height:20px; text-decoration:none;}");
document.writeln(".topwhite:hover{font-size:12px;color:#FFFFFF;text-decoration:none;line-height:20px; text-decoration:none;}");
document.writeln(".topwhite:visited{font-size:12px;color:#FFFFFF;line-height:20px; text-decoration:none;}");
document.writeln(".toplist:link{font-size:12px;color:#000000;line-height:20px; text-decoration:none;}");
document.writeln(".toplist:visited{font-size:12px;color:#000000;line-height:20px; text-decoration:none;}");
document.writeln(".toplist:hover{font-size:12px;color:#B70300;text-decoration:none;line-height:20px; text-decoration:none;}");
document.writeln(".toplist:active{font-size:12px;color:#B70300;text-decoration:none;line-height:20px; text-decoration:none;}");
document.writeln(".menu{font-size:12px;color:#FFFFFF;letter-spacing:0.5em;border-bottom:1px white solid;text-decoration:none;}");
document.writeln(".menu td{font-size:12px;color:#FFFFFF;letter-spacing:0.5em; text-decoration:none;}");
document.writeln(".menu a:link{font-size:12px;color:#FFFFFF;letter-spacing:0.5em; text-decoration:none;}");
document.writeln(".menu a:hover{font-size:12px;color:#FFFFFF;letter-spacing:0.5em;text-decoration:none;}");
document.writeln(".menu a:visited{font-size:12px;color:#FFFFFF;letter-spacing:0.5em;text-decoration:none;}");
document.writeln(".white:link{font-size:12px;color:#FFFFFF;text-decoration:none;}");
document.writeln(".white:hover{font-size:12px;color:#FFFFFF;text-decoration:none;}");
document.writeln(".white:visited{font-size:12px;color:#FFFFFF;text-decoration:none;}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<script language=\"JavaScript\" type=\"text\/JavaScript\">");
document.writeln("<!--");
document.writeln("function MM_reloadPage(init) {  \/\/reloads the window if Nav4 resized");
document.writeln("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {");
document.writeln("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}");
document.writeln("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();");
document.writeln("}");
document.writeln("MM_reloadPage(true);");
document.writeln("\/\/ -->");
document.writeln("function MM_findObj(n, d) { \/\/v4.01");
document.writeln("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
document.writeln("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
document.writeln("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
document.writeln("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);");
document.writeln("  if(!x && d.getElementById) x=d.getElementById(n); return x;");
document.writeln("}");
document.writeln("function MM_showHideLayers() { \/\/v6.0");
document.writeln("  var i,p,v,obj,args=MM_showHideLayers.arguments;");
document.writeln("  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];");
document.writeln("    if (obj.style) { obj=obj.style; v=(v==\'show\')?\'visible\':(v==\'hide\')?\'hidden\':v; }");
document.writeln("    obj.visibility=v; }");
document.writeln("}");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<\/head>");
document.writeln("<body>");
document.writeln("<div id=\"icxoLayer1\" style=\"position:absolute; left:114px; top:20px; width:198px; height:43px; z-index:11; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer1\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer1\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/biz.icxo.com\/\" target=\"_blank\" class=\"toplist\">商业报道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/economist.icxo.com\/\" target=\"_blank\" class=\"toplist\">经济学人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/tv.icxo.com\/\" target=\"_blank\" class=\"toplist\">商务电视<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/finance.icxo.com\/\" target=\"_blank\" class=\"toplist\">财经报道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/tech.icxo.com\/\" target=\"_blank\" class=\"toplist\">科技频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/media.icxo.com\/\" target=\"_blank\" class=\"toplist\">媒体频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer2\" style=\"position:absolute; left:178px; top:20px; width:198px; height:43px; z-index:12; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer2\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer2\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/elab.icxo.com\/\" target=\"_blank\" ");
document.writeln("");
document.writeln("class=\"toplist\">创业互动<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/oxford.icxo.com\/\" target=\"_blank\" class=\"toplist\">管理实务<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/brand.icxo.com\/\" target=\"_blank\" class=\"toplist\">品牌频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/data.icxo.com\/\" target=\"_blank\" class=\"toplist\">数据频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/mkt.icxo.com\/\" target=\"_blank\" class=\"toplist\">市场营销<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/abroad.icxo.com\/\" target=\"_blank\" class=\"toplist\">出国频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer3\" style=\"position:absolute; left:239px; top:20px; width:198px; height:43px; z-index:13; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer3\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer3\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/ceo.icxo.com\/\" target=\"_blank\" ");
document.writeln("");
document.writeln("class=\"toplist\"><strong>CEO<\/strong>频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/cfo.icxo.com\/\" target=\"_blank\" class=\"toplist\">CFO频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/cto.icxo.com\/\" target=\"_blank\" class=\"toplist\">CTO频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/cio.icxo.com\/\" target=\"_blank\" class=\"toplist\">CIO频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/cmo.icxo.com\/\" target=\"_blank\" class=\"toplist\">CMO频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/cho.icxo.com\/\" target=\"_blank\" class=\"toplist\">CHO频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer4\" style=\"position:absolute; left:302px; top:20px; width:396px; height:67px; z-index:14; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer4\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer4\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td bgcolor=\"#E8E8E8\"><div align=\"center\"><a href=\"http:\/\/motor.icxo.com\/\" target=\"_blank\" ");
document.writeln("");
document.writeln("class=\"toplist\">汽车频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/re.icxo.com\/\" target=\"_blank\" class=\"toplist\">地产频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/it.icxo.com\/\" target=\"_blank\" class=\"toplist\">电脑频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/food.icxo.com\/\" target=\"_blank\" class=\"toplist\">食品频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/machine.icxo.com\/\" target=\"_blank\" class=\"toplist\">机械频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/chem.icxo.com\/\" target=\"_blank\" class=\"toplist\">化工频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bm.icxo.com\/\" target=\"_blank\" class=\"toplist\">建材频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/fashion.icxo.com\/\" target=\"_blank\" class=\"toplist\">时装频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/ee.icxo.com\/\" target=\"_blank\" class=\"toplist\">电子频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a ");
document.writeln("");
document.writeln("href=\"http:\/\/app.icxo.com\/\" target=\"_blank\" class=\"toplist\">家电频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/drug.icxo.com\/\" target=\"_blank\" class=\"toplist\">医药频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/textile.icxo.com\/\" target=\"_blank\" class=\"toplist\">纺织频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/energy.icxo.com\/\" target=\"_blank\" class=\"toplist\">能源频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/agri.icxo.com\/\" target=\"_blank\" class=\"toplist\">农业频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/transport.icxo.com\/\" target=\"_blank\" class=\"toplist\">交通频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/pack.icxo.com\/\" target=\"_blank\" class=\"toplist\">包装频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a ");
document.writeln("");
document.writeln("href=\"http:\/\/arch.icxo.com\/\" target=\"_blank\" class=\"toplist\">建筑频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/events.icxo.com\/\" target=\"_blank\" class=\"toplist\">会展频道<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer5\" style=\"position:absolute; left:366px; top:20px; width:198px; height:43px; z-index:15; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer5\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer5\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td bgcolor=\"#E8E8E8\"><div align=\"center\"><a href=\"http:\/\/bbs.icxo.com\/\" target=\"_blank\" ");
document.writeln("");
document.writeln("class=\"toplist\">商道社区<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/blog.icxo.com\/\" target=\"_blank\" class=\"toplist\">商业博客<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/salon.icxo.com\/\" target=\"_blank\" class=\"toplist\">经理沙龙<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/digest.icxo.com\/\" target=\"_blank\" class=\"toplist\">读者文摘<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/ask.icxo.com\/\" target=\"_blank\" class=\"toplist\">商人问吧<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bp.icxo.com\/\" target=\"_blank\" class=\"toplist\">商人医院<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer6\" style=\"position:absolute; left:429px; top:20px; width:198px; height:67px; z-index:16; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer6\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer6\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/wei.icxo.com\/\" target=\"_blank\" class=\"toplist\">经理学院<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/book.icxo.com\/\" target=\"_blank\" class=\"toplist\">经理书架<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/trip.icxo.com\/\" target=\"_blank\" class=\"toplist\">世界商旅<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/certify.icxo.com\/\" target=\"_blank\" class=\"toplist\">经理认证<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/inc.icxo.com\/\" target=\"_blank\" class=\"toplist\">商务消息<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bi.icxo.com\/\" target=\"_blank\" class=\"toplist\">商业情报<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/school.icxo.com\/\" target=\"_blank\" class=\"toplist\">经理学堂<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/office.icxo.com\/\" target=\"_blank\" class=\"toplist\">办公伙伴<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/job.icxo.com\/\" class=\"toplist\">人力银行<\/a> <\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer7\" style=\"position:absolute; left:492px; top:20px; width:198px; height:43px; z-index:17; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer7\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer7\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/ent.icxo.com\/\" target=\"_blank\" class=\"toplist\">娱乐报道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/lady.icxo.com\/\" target=\"_blank\" class=\"toplist\">伊人风尚<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/man.icxo.com\/\" target=\"_blank\" class=\"toplist\">男人帮<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/design.icxo.com\/\" target=\"_blank\" class=\"toplist\">哈佛设计<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/fol.icxo.com\/\" target=\"_blank\" class=\"toplist\">时尚通讯<\/a><a href=\"http:\/\/luxury.icxo.com\/\" target=\"_blank\" class=\"toplist\"><\/a> <\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/luxury.icxo.com\/\" target=\"_blank\" class=\"toplist\">奢侈品<\/a><a href=\"http:\/\/fol.icxo.com\/\" target=\"_blank\" class=\"toplist\"><\/a> <\/div><\/td>");
document.writeln("    <\/tr><tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/health.icxo.com\/\" target=\"_blank\" class=\"toplist\">健康频道<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bbs.icxo.com\/index.asp?boardid=1703\" target=\"_blank\" class=\"toplist\">口口相传<\/a><a href=\"http:\/\/luxury.icxo.com\/\" target=\"_blank\" class=\"toplist\"><\/a><\/div><\/td>");
document.writeln("      <td><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<div id=\"icxoLayer8\" style=\"position:absolute; left:555px; top:20px; width:198px; height:67px; z-index:18; visibility: ");
document.writeln("");
document.writeln("hidden;\">");
document.writeln("  <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"#FFFFFF\"");
document.writeln("  onmouseover=\"MM_showHideLayers(\'icxoLayer8\',\'\',\'show\')\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer8\',\'\',\'hide\')\">");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/sh.icxo.com\/\" target=\"_blank\" class=\"toplist\">上海经理人<\/a><\/div><\/td>");
document.writeln("      <td bgcolor=\"#E8E8E8\"><div align=\"center\"><a href=\"http:\/\/bj.icxo.com\/\" target=\"_blank\" ");
document.writeln("");
document.writeln("class=\"toplist\">北京经理人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/gd.icxo.com\/\" target=\"_blank\" class=\"toplist\">广东经理人<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/hk.icxo.com\/\" target=\"_blank\" class=\"toplist\">香港经理人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bbs.icxo.com\/index.asp?boardid=1923\" target=\"_blank\" class=\"toplist\">浙江经理人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/bbs.icxo.com\/index.asp?boardid=1933\" target=\"_blank\" class=\"toplist\">江苏经理人<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr bgcolor=\"#E8E8E8\">");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/asia.icxo.com\/\" target=\"_blank\" class=\"toplist\">亚洲经理人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/euro.icxo.com\/\" target=\"_blank\" class=\"toplist\">欧洲经理人<\/a><\/div><\/td>");
document.writeln("      <td><div align=\"center\"><a href=\"http:\/\/usa.icxo.com\/\" target=\"_blank\" class=\"toplist\">美国经理人<\/a><\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("<\/div>");
document.writeln("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"888888\" style=\"border-bottom:1px white solid\">");
document.writeln("  <tr>");
document.writeln("    <td onMouseOver=\"this.style.backgroundColor=\'#B3B3B3\'\" onMouseOut=\"this.style.backgroundColor=\'#888888\'\"width=\"110\">");
document.writeln("	 <div align=\"center\" class=\"ytext\"><a href=\"http:\/\/www.icxo.com\/\" ");
document.writeln("");
document.writeln("target=\"_blank\"class=\"top\">世界经理人主页<\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer1\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer1\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"http:\/\/biz.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>商业评论<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer2\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer2\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"#\" class=\"topwhite\"><font color=#FFFFFF>战略管理<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer3\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer3\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"#\" class=\"topwhite\"><font color=#FFFFFF>企业领袖<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer4\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer4\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"http:\/\/oxford.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>产业中心<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer5\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer5\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"http:\/\/finance.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>商务互动<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer6\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer6\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"#\" class=\"topwhite\"><font color=#FFFFFF>经理协会<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer7\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer7\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"#\" class=\"topwhite\"><font color=#FFFFFF>时尚格调<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"MM_showHideLayers(\'icxoLayer8\',\'\',\'show\');this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"MM_showHideLayers(\'icxoLayer8\',\'\',\'hide\');this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"http:\/\/online.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>国家区域<\/font><\/a><\/div><\/td>");
document.writeln("    <td width=\"62\"");
document.writeln("	onmouseover=\"this.style.backgroundColor=\'#B3B3B3\'\"");
document.writeln("	onmouseout=\"this.style.backgroundColor=\'#888888\'\"><div ");
document.writeln("");
document.writeln("align=\"center\"><a href=\"http:\/\/bbs.icxo.com\/\" class=\"topwhite\"><font color=#FFFFFF>商道社区<\/font><\/a><\/div><\/td>");
document.writeln("    <td onMouseOver=\"this.style.backgroundColor=\'#B3B3B3\'\" onMouseOut=\"this.style.backgroundColor=\'#888888\'\"width=\"62\">");
document.writeln("    <div align=\"center\"><a href=\"http:\/\/blog.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>商业博客<\/font><\/a><\/div><\/td>");
document.writeln("    <td onMouseOver=\"this.style.backgroundColor=\'#B3B3B3\'\" onMouseOut=\"this.style.backgroundColor=\'#888888\'\"width=\"62\">");
document.writeln("    <div align=\"center\"><a href=\"http:\/\/digest.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>经理文摘<\/font><\/a><\/div><\/td>");
document.writeln("    <td onMouseOver=\"this.style.backgroundColor=\'#B3B3B3\'\" onMouseOut=\"this.style.backgroundColor=\'#888888\'\"width=\"62\">");
document.writeln("    <div align=\"center\"><a href=\"http:\/\/salon.icxo.com\/\" target=\"_blank\"class=\"topwhite\"><font ");
document.writeln("");
document.writeln("color=#FFFFFF>经理沙龙<\/font><\/a><\/div><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<\/body>");
document.writeln("<\/html>")